### ISSUE TITLE
lime-qml start fails

### ISSUE THREAD

**Issue by darkstar999** [limetext/lime-qml#16]
Startup  on arch via
 alias lime-qml="cd $GOPATH/src/github.com/limetext/lime-qml/main && git submodule update --recursive && go build && ./main"

ERROR
[02/18/16 23:07:23] [EROR] Failed to register command nop: Command wasn't registered in any list: nop
[02/18/16 23:07:23] [DEBG] calling newEngine
[02/18/16 23:07:23] [DEBG] calling newEngine
[02/18/16 23:07:23] [INFO] Initializing
[02/18/16 23:07:23] [INFO] Initializing
[02/18/16 23:07:24] [INFO] Loaded ../packages/Default/Default.sublime-keymap
[02/18/16 23:07:24] [INFO] Loaded ../packages/Default/Default (Linux).sublime-keymap
[02/18/16 23:07:24] [INFO] Loaded ../packages/Default/Default.sublime-keymap
[02/18/16 23:07:24] [INFO] Loaded ../packages/Default/Default (Linux).sublime-keymap
[02/18/16 23:07:24] [INFO] Loaded ../packages/User/Default.sublime-keymap
[02/18/16 23:07:24] [INFO] Loaded ../packages/User/Default (Linux).sublime-keymap
[02/18/16 23:07:24] [DEBG] ../packages/User is watched already
[02/18/16 23:07:24] [INFO] Loaded ../packages/Default/Preferences.sublime-settings
[02/18/16 23:07:24] [INFO] Loaded ../packages/Default/Preferences (Linux).sublime-settings
[02/18/16 23:07:24] [INFO] Loaded ../packages/User/Preferences.sublime-settings
[02/18/16 23:07:24] [DEBG] ../packages/User is watched already
[02/18/16 23:07:24] [DEBG] OnInit callbacks executing
[02/18/16 23:07:24] [INFO] Loaded ../packages/User/Default.sublime-keymap
[02/18/16 23:07:24] [INFO] Loaded ../packages/User/Default (Linux).sublime-keymap
[02/18/16 23:07:24] [DEBG] ../packages/User is watched already
[02/18/16 23:07:24] [INFO] Loaded ../packages/Default/Preferences.sublime-settings
[02/18/16 23:07:24] [INFO] Loaded ../packages/Default/Preferences (Linux).sublime-settings
[02/18/16 23:07:24] [INFO] Loaded ../packages/User/Preferences.sublime-settings
[02/18/16 23:07:24] [DEBG] ../packages/User is watched already
[02/18/16 23:07:24] [DEBG] OnInit callbacks executing
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
panic(0x7edbc0, 0xc8203ec040)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
gopkg.in/qml%2ev1._cgoCheckPointer0(0x7573c0, 0xc8203ec010, 0xc8203ec020, 0x1, 0x1, 0x2256c50)
        ??:0 +0x4d
gopkg.in/qml%2ev1.(*Common).On.func1()
        /home/darkstar999/git/go/src/gopkg.in/qml.v1/qml.go:802 +0x1e3
gopkg.in/qml%2ev1.hookIdleTimer()
        /home/darkstar999/git/go/src/gopkg.in/qml.v1/bridge.go:190 +0x5d
gopkg.in/qml%2ev1._cgoexpwrap_0ae46c052b10_hookIdleTimer()
        ??:0 +0x14
gopkg.in/qml%2ev1._Cfunc_applicationExec()
        ??:0 +0x36
gopkg.in/qml%2ev1.Run(0xc820344f40, 0x0, 0x0)
        /home/darkstar999/git/go/src/gopkg.in/qml.v1/bridge.go:63 +0x16e
main.main()
        /home/darkstar999/git/go/src/github.com/limetext/lime-qml/main/main.go:37 +0x1e3

Is there any solution?

**Comment by erbridge** [comment]
What version of `go` are you running?

**Comment by akarki15** [comment]
Im getting the same error. should this have been reported to lime-backend though?

**Comment by akarki15** [comment]
@darkstar999, does the front-end start ?

**Comment by zoli** [comment]
No it doesn't currently(at least on my system).

**Comment by erbridge** [comment]
Go 1.6 changed the way it handles shared pointers with C, which I suspect is the culprit here.

**Comment by erbridge** [comment]
See https://tip.golang.org/cmd/cgo/#hdr-Passing_pointers.

**Comment by akarki15** [comment]
im on go 1.5.1. although the front-end starts, i get the following error when it starts: 

```
Failed to register command nop: Command wasn't registered in any list: nop
```

**Comment by zoli** [comment]
Thanks @erbridge, also we can set `GODEBUG=cgocheck=0` environment variable in go 1.6 to disable this.

@akarki15 Thats because nop command has not been implemented yet.

**Comment by erbridge** [comment]
We can disable the checks, but better would be to fix the errors they reveal, I think.

**Comment by zoli** [comment]
related to https://github.com/go-qml/qml/issues/170
