### ISSUE TITLE
lime-qml crashes when using RGBA and render

### ISSUE THREAD

**Issue by zgiles** [limetext/lime-qml#23]
I've gotten lime-qmp/main to build. When it runs, it crashes with a panic that something is null

Specifically:

```
2016/04/25 19:49:58 View.qml:50: Buffer: updateMyView:  frontendView(0x7c7be50)
[04/25/16 19:49:58] [INFO] Fix: &{0xfa9eab0 0xc82022e150}  59  7452
2016/04/25 19:49:58 Buffer.qml:457: Bad currentSelection! null
[04/25/16 19:49:58] [INFO] Python sez:
[04/25/16 19:49:58] [INFO] Python sez:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x4005999]

goroutine 1 [running, locked to thread]:
main.(*qmlfrontend).DefaultBg(0xc820275170, 0x0)
    /Users/zrg/go/src/github.com/limetext/lime-qml/main/frontend.go:131 +0x99
reflect.Value.call(0x442c840, 0xc820275170, 0x313, 0x444b210, 0x4, 0xc820405ad8, 0x0, 0xa, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x442c840, 0xc820275170, 0x313, 0xc820405ad8, 0x0, 0xa, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:300 +0xb1
github.com/limetext/qml-go.hookGoValueCallMethod(0x7c1a1f0, 0xc820240000, 0x7fff00000001, 0x7fff5fbfcd40)
    /Users/zrg/go/src/github.com/limetext/qml-go/bridge.go:515 +0x425
github.com/limetext/qml-go._Cfunc_componentCreateWindow(0x7d66c50, 0x0, 0x0)
    ??:0 +0x36
```

Based on this, I assume `DefaultBg` was the issue.
Changing the return of `DefaultBg` (and `DefaultFg`) to a constant, it returns properly and lime-qml runs.. but with bad colors.

Changed code that makes it run instead of crash:

```
@@ -18,7 +18,6 @@ import (
        "github.com/limetext/backend"
        "github.com/limetext/backend/keys"
        "github.com/limetext/backend/log"
-       "github.com/limetext/backend/render"
        . "github.com/limetext/text"
        "github.com/limetext/util"
 )
@@ -128,15 +127,11 @@ func (t *qmlfrontend) qmlChanged(value, field interface{}) {
 }

 func (t *qmlfrontend) DefaultBg() color.RGBA {
-       c := t.ColorScheme().Spice(&render.ViewRegions{})
-       c.Background.A = 0xff
-       return color.RGBA(c.Background)
+       return color.RGBA{ R: 100, G: 105, B: 255, A: 0}
 }

 func (t *qmlfrontend) DefaultFg() color.RGBA {
-       c := t.ColorScheme().Spice(&render.ViewRegions{})
-       c.Foreground.A = 0xff
-       return color.RGBA(c.Foreground)
+       return color.RGBA{ R: 255, G: 100, B: 255, A: 0}
 }
```

My guess is that likely `render.ViewRegions{}` is broke, but I don't know enough about it.

Will research more, but if someone knows, perhaps it's an easy fix.

**Comment by zoli** [comment]
Probably [`ColorScheme()`](https://github.com/limetext/lime-qml/blob/master/main/frontend.go#L272) is returning `nil`. Is packages submodule updated?

**Comment by ricochet1k** [comment]
Yeah, I got exactly the same issue. Make sure to run `git submodule update --init --recursive`.

@zoli Updating lime-qml is rather complex right now. We need to make it easier somehow.

**Comment by zoli** [comment]
Personally the issue that bothers me is the glide.lock file because all repositories are in development and the lock file needs to be updated each time, About the submodules I think we can change the makefile to suit our needs.

@ricochet1k other than these difficulties what other issues are you facing?

**Comment by zgiles** [comment]
@zoli you're right.. I didn't realize submodules were recursive. Ok, I updated that and it compiles fine, but still errors when it hits the line. ( I stashed all my changes to get back to clean code )

@ricochet1k you don't get a segfault when running?

```
[04/26/16 16:16:36] [DEBG] calling newEngine
[04/26/16 16:16:36] [DEBG] setvar frontend
[04/26/16 16:16:36] [DEBG] setvar editor
[04/26/16 16:16:36] [DEBG] loadfile
2016/04/26 16:16:37 View.qml:50: Buffer: updateMyView:  frontendView(0x105766b0)
[04/26/16 16:16:37] [INFO] Fix: &{0x7dc4640 0xc820292f30}  107  14801
2016/04/26 16:16:37 Buffer.qml:457: Bad currentSelection! null
[04/26/16 16:16:37] [INFO] Python sez: Exception ignored in: <module 'threading' from '/opt/boxen/homebrew/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py'>
[04/26/16 16:16:37] [INFO] Python sez: Traceback (most recent call last):
[04/26/16 16:16:37] [INFO] Python sez:   File "/opt/boxen/homebrew/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 1283, in _shutdown
[04/26/16 16:16:37] [INFO] Python sez:     assert tlock.locked()
[04/26/16 16:16:37] [INFO] Python sez: AssertionError:
[04/26/16 16:16:37] [INFO] Python sez:
[04/26/16 16:16:37] [INFO] Python sez:
[04/26/16 16:16:37] [INFO] Python sez:
[04/26/16 16:16:37] [INFO] Python sez:
[04/26/16 16:16:37] [INFO] Python sez:
[04/26/16 16:16:37] [INFO] Python sez:
[04/26/16 16:16:37] [INFO] Python sez:
[04/26/16 16:16:37] [INFO] Python sez:
[04/26/16 16:16:37] [INFO] Python sez:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x4005999]

goroutine 1 [running, locked to thread]:
main.(*qmlfrontend).DefaultBg(0xc82025d1a0, 0x0)
    /Users/zrg/go/src/github.com/limetext/lime-qml/main/frontend.go:131 +0x99
reflect.Value.call(0x442c840, 0xc82025d1a0, 0x313, 0x444b210, 0x4, 0xc82056dad8, 0x0, 0xa, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x442c840, 0xc82025d1a0, 0x313, 0xc82056dad8, 0x0, 0xa, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:300 +0xb1
github.com/limetext/qml-go.hookGoValueCallMethod(0x6ffb4c0, 0xc820226050, 0x1, 0x7fff5fbfcd30)
    /Users/zrg/go/src/github.com/limetext/qml-go/bridge.go:515 +0x425
```

**Comment by ricochet1k** [comment]
@zgiles Run `go get -v ./...` and then build and run again.

**Comment by zgiles** [comment]
Interesting. I wouldn't have thought of doing `get` on `./...`. 
I did it, but got the same error. I also tried a get / update / recompile on `$GOROOT/src/github.com/limetext/...` and same error.

I decided to see if I'm crazy or not.. I made a new GOROOT and started the install from scratch. That worked.

So, I think this can be marked as resolved. I think I'll mark it up as just complicated building mixed with the missing knowledge of git submodules.

**Comment by zgiles** [comment]
Build instructions for anyone who happens to look here...

```
export PKG_CONFIG_PATH=`brew --prefix python3`/Frameworks/Python.framework/Versions/3.4/lib/pkgconfig:`brew --prefix qt5`/lib/pkgconfig:`brew --prefix oniguruma`/lib/pkgconfig
go get github.com/limetext/backend/...
cd $GOPATH/src/github.com/limetext/backend
git submodule update --init --recursive
cd -
go test github.com/limetext/backend/...
go get github.com/limetext/lime-qml/...
cd $GOPATH/src/github.com/limetext/lime-qml
git submodule update --init --recursive
cd main/
go build
ulimit -n 1024
./main
```

Thanks for the help guys.. will start to test and poke at it now that I can open it.
Also, interesting that I don't up the ulimit, then it errors as too many files open, which seems silly that an editor needs more than 256 open files to start. Is there another Issue for that already?

```
[04/26/16 17:06:46] [WARN] Error on reading directory ../packages/Markdown, open ../packages/Markdown: too many open files
```

**Comment by zoli** [comment]
> which seems silly that an editor needs more than 256 open files to start. Is there another Issue for that already?

No there isn't and I haven't seen this issue before. Maybe we are watching to many files. Is there a way to list open files by lime?

**Comment by zgiles** [comment]
Moving my comment etc about open files to an open files issue #24
