### ISSUE TITLE
panic: runtime error: cgo result has Go pointer

### ISSUE THREAD

**Issue by Naruto0** [limetext/lime-qml#35]
Ubuntu 16.04, successfuly built lime-qml, but not withou ta problem...

```
me@mymachine:~/gopath/src/github.com/limetext/lime-qml/main$ ./main 
[07/18/16 20:50:24] [INFO] Initializing
[07/18/16 20:50:24] [DEBG] OnInit callbacks executing
[07/18/16 20:50:25] [DEBG] OnInit callbacks finished
[07/18/16 20:50:25] [DEBG] Scanning ../packages for packages
[07/18/16 20:50:25] [DEBG] Loading package ASP
[07/18/16 20:50:25] [DEBG] Loading package ActionScript
[07/18/16 20:50:25] [DEBG] Loading package AppleScript
[07/18/16 20:50:25] [DEBG] Loading package Batch File
[07/18/16 20:50:25] [DEBG] Loading package C#
[07/18/16 20:50:25] [DEBG] Loading package C++
[07/18/16 20:50:25] [DEBG] Loading package CSS
[07/18/16 20:50:25] [DEBG] Loading plugin CSS.css_completions
[07/18/16 20:50:25] [INFO] Python sez: Loading plugin CSS.css_completions
[07/18/16 20:50:25] [DEBG] Loading package Clojure
[07/18/16 20:50:25] [DEBG] Loading package D
[07/18/16 20:50:25] [DEBG] Loading package Default
[07/18/16 20:50:25] [DEBG] Loading plugin Default.history_list
[07/18/16 20:50:25] [INFO] Python sez: Loading plugin Default.history_list
[07/18/16 20:50:25] [DEBG] Loading package Diff
[07/18/16 20:50:25] [DEBG] Loading plugin Diff.diff
[07/18/16 20:50:25] [INFO] Python sez: Loading plugin Diff.diff
panic: runtime error: cgo result has Go pointer

goroutine 34 [running]:
panic(0x835180, 0xc82025f4d0)
    /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/limetext/gopy/lib._cgoexpwrap_14798609a186_goGenericAlloc.func1(0xc820350f80)
    ??:0 +0x3a
github.com/limetext/gopy/lib._cgoexpwrap_14798609a186_goGenericAlloc(0x26bdbe0, 0x0, 0xc8204a7240)
    ??:0 +0x6f
github.com/limetext/gopy/lib._Cfunc_typeAlloc(0x26bdbe0, 0x0, 0x0)
    ??:0 +0x42
github.com/limetext/gopy/lib.(*Type).Alloc(0x26bdbe0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/me/gopath/src/github.com/limetext/gopy/lib/type.go:40 +0xd9
github.com/limetext/gopy/lib.goClassNew(0x26bdbe0, 0x7f223a307400, 0x0, 0x4b25e0)
    /home/me/gopath/src/github.com/limetext/gopy/lib/class.go:449 +0x35d
github.com/limetext/gopy/lib._cgoexpwrap_14798609a186_goClassNew(0x26bdbe0, 0x7f223a307400, 0x0, 0x0)
    ??:0 +0x6e
github.com/limetext/gopy/lib._Cfunc_PyObject_CallObject(0x7f2239ff9ea0, 0x7f225c05e7f0, 0x0)
    ??:0 +0x42
github.com/limetext/gopy/lib.(*BaseObject).CallMethodObjArgs(0x7f225c059e08, 0x8ca9e0, 0xd, 0xc820351540, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
    /home/me/gopath/src/github.com/limetext/gopy/lib/base.go:230 +0x6c7
github.com/limetext/sublime.(*plugin).Load(0xc82008c360)
    /home/me/gopath/src/github.com/limetext/sublime/plugin.go:40 +0x469
github.com/limetext/sublime.(*pkg).loadPlugin(0xc8203be790, 0xc82008c2e0, 0x18)
    /home/me/gopath/src/github.com/limetext/sublime/package.go:122 +0xcd
github.com/limetext/sublime.(*pkg).loadPlugins(0xc8203be790)
    /home/me/gopath/src/github.com/limetext/sublime/package.go:115 +0x5f5
github.com/limetext/sublime.(*pkg).Load(0xc8203be790)
    /home/me/gopath/src/github.com/limetext/sublime/package.go:86 +0x1ef
github.com/limetext/backend/packages.load(0x7f2239f8d238, 0xc8203be790)
    /home/me/gopath/src/github.com/limetext/backend/packages/package.go:109 +0x2b
github.com/limetext/backend/packages.Scan.func1(0xc820059000, 0x2f, 0x40)
    /home/me/gopath/src/github.com/limetext/backend/packages/package.go:83 +0x82
github.com/limetext/backend/packages.Scan(0x8c0410, 0xb)
    /home/me/gopath/src/github.com/limetext/backend/packages/package.go:85 +0x5d9
github.com/limetext/backend.(*PathEvent).call(0xcfab00, 0x8c0410, 0xb)
    /home/me/gopath/src/github.com/limetext/backend/events.go:141 +0x258
github.com/limetext/backend.(*Editor).AddPackagesPath(0xc820066c00, 0x8c0410, 0xb)
    /home/me/gopath/src/github.com/limetext/backend/editor.go:412 +0x8e
main.(*frontend).loop(0xc8202f72c0, 0x0, 0x0)
    /home/me/gopath/src/github.com/limetext/lime-qml/main/frontend.go:385 +0x15b
main.(*frontend).(main.loop)-fm(0x0, 0x0)
    /home/me/gopath/src/github.com/limetext/lime-qml/main/frontend.go:57 +0x2e
github.com/limetext/qml-go.Run.func1(0xc8203a6000, 0xc820395420)
    /home/me/gopath/src/github.com/limetext/qml-go/bridge.go:69 +0x2d
created by github.com/limetext/qml-go.Run
    /home/me/gopath/src/github.com/limetext/qml-go/bridge.go:71 +0x169
```

**Comment by zoli** [comment]
Read https://github.com/limetext/lime/wiki/Building-on-Ubuntu-16.04 related to #16.

**Comment by Naruto0** [comment]
Thanks!
